[Encoder]
	Name=embedding

[Decoder]
	Name=complex
	RegularizationParameter=0.01

[Shared]
	CodeDimension=500

[Optimizer]
	MaxGradientNorm=1
	ReportTrainLossEvery=100

	[EarlyStopping]
		CheckEvery=2000
		BurninPhaseDuration=6000

	[Algorithm]
		Name=Adam
		learning_rate=0.01

[General]
	NegativeSampleRate=10
	GraphSplitSize=0.5
	ExperimentName=models/Distmult
	GraphBatchSize=30000

[Evaluation]
	Metric=MRR
