[Encoder]
	Name=gcn-full
	RegularizationParameter=0.01
	NumberOfConvolutions=2
	DropoutProbability=0.1
	UseGlobalNorm=False


[Decoder]
	Name=distmult

[Shared]
	EmbeddingWidth=100

[Optimizer]
	Minibatches=No
	MaxGradientNorm=1
	ReportTrainLossEvery=100

	[EarlyStopping]
		CheckEvery=500
		BurninPhaseDuration=5000

	[Algorithm]
		Name=Adam
		learning_rate=0.01

[General]
	NegativeSampleRate=2
	Backend=theano

