[Encoder]
	Name=gcn-diag-assumed
	RegularizationParameter=0.01
	MessageDropoutProbability=0.3
	NumberOfConvolutions=1

[Decoder]
	Name=distmult

[Shared]
	EmbeddingWidth=200

[Optimizer]
	Minibatches=Yes
	MaxGradientNorm=1
	ReportTrainLossEvery=10	
	BatchSize=10

	[EarlyStopping]
		CheckEvery=100
		BurninPhaseDuration=2000

	[Algorithm]
		Name=Adam
		learning_rate=0.001

[General]
	NegativeSampleRate=10
	Backend=tensorflow

