[Encoder]
	Name=gcn_diag
	DropoutKeepProbability=1.0
	InternalEncoderDimension=200
	NumberOfLayers=1
	UseOutputTransform=No

[Decoder]
	Name=bilinear-diag
	RegularizationParameter=0.01

[Shared]
	CodeDimension=200

[Optimizer]
	MaxGradientNorm=1
	ReportTrainLossEvery=20

	[EarlyStopping]
		CheckEvery=60
		BurninPhaseDuration=5000

	[Algorithm]
		Name=Adam
		learning_rate=0.01

[General]
	NegativeSampleRate=1
	GraphSplitSize=20000

[Evaluation]
	Metric=MRR