[Encoder]
	Name=gcn_diag_sigmoid_gate
	DropoutKeepProbability=0.7
	InternalEncoderDimension=100

[Decoder]
	Name=bilinear-diag
	RegularizationParameter=0.01

[Shared]
	CodeDimension=50

[Optimizer]
	Minibatches=No
	MaxGradientNorm=1
	ReportTrainLossEvery=50

	[EarlyStopping]
		CheckEvery=1000
		BurninPhaseDuration=5000

	[Algorithm]
		Name=Adam
		learning_rate=0.01

[General]
	NegativeSampleRate=1