[Encoder]
	Name=gcn-full
	RegularizationParameter=0.0
	NumberOfConvolutions=2
	DropoutProbability=0.2
	UseGlobalNorm=True


[Decoder]
	Name=distmult

[Shared]
	EmbeddingWidth=100

[Optimizer]
	Minibatches=No
	MaxGradientNorm=1
	ReportTrainLossEvery=500

	[EarlyStopping]
		CheckEvery=2500
		BurninPhaseDuration=20000

	[Algorithm]
		Name=Adam
		learning_rate=0.01

[General]
	NegativeSampleRate=1
	Backend=theano

